### ISSUE TITLE
Review notes

### ISSUE THREAD

**Issue by chrisvfritz** [pearmans/look_at_cats#1]
:+1: This looks fantastic. :tada: :balloon: Things I like:
- Bootstrap integration
- Using SCSS
- Using CoffeeScript! :tada: 
- Included a well-labeled form for cat pictures

Way above and beyond here and I love it, so I've spent a little more time on this feedback than usual and actually have submitted a pull request, with 6 refactors to help you learn how you could improve the project even further. Each refactor is in its own commit, which I'll summarize below:
#### [modified bootstrap integration to use the bootstrap-sass gem](https://github.com/chrisvfritz/look_at_cats/commit/204b33f03a6be79a2b4c9854afc91b2d457b330c)

Some advantages of this gem are you can:
- override [Bootstrap variables](http://getbootstrap.com/customize/#less-variables) before compilation
- use Bootstrap variables and mixins in your own SCSS
- very easily manage which parts of Bootstrap you'd like to include, in case you decide you want to slim down
#### [converted all indentation to 2-space soft-tabs](https://github.com/chrisvfritz/look_at_cats/commit/35fa241690ac3a8448b226e0ea5547ca6bd41b31)

The standard indentation for Ruby (`.rb`) files is two-space soft-tabs. And in Rails projects, it's actually best practice to have _every_ file use two-space soft-tabs.

[Here's how you can reconfigure your text editor](https://github.com/chrisvfritz/tc359_cheatsheets/blob/master/ruby/indentation.md) to use two-space soft-tabs instead. And then afterwards, to update any pre-existing files, you may also find [this video](https://www.youtube.com/watch?v=_JFIeY46sIU) and [this video](https://www.youtube.com/watch?v=GMf8dlrEbB4) helpful for Sublime Text.
#### [reorganized gemfile and slimmed down all the views](https://github.com/chrisvfritz/look_at_cats/commit/8cdf864ccccb34a90a489cb60aaf0b48b61708a0)

As a Gemfile gets larger, I like to separate gems into different sections to make them easier to manage. I also converted all our ERB to slim here, which allows us to be much lazier when writing HTML. :smiley: 
#### [included more rails helpers in the views](https://github.com/chrisvfritz/look_at_cats/commit/bcf92a3b3450ee1415e688adcf3361b8e9bc7789)

Rails has a ton of helper methods for everything from [automatically pluralizing words](https://github.com/chrisvfritz/look_at_cats/commit/bcf92a3b3450ee1415e688adcf3361b8e9bc7789#diff-1eb592094d8cb08223821ad11d3c42a5R4) to [creating forms](https://github.com/chrisvfritz/look_at_cats/commit/bcf92a3b3450ee1415e688adcf3361b8e9bc7789#diff-389e5361121f8c78f1f4ed4f0442e25aR1). When they exist, it's usually a good idea to use them, as they'll do some things for you, like automatically setting values for form fields.
#### [tightened bootstrap integration](https://github.com/chrisvfritz/look_at_cats/commit/79bebe3ed651850455c5c284810d598a0776d415)

I used some more features of Bootstrap, to avoid reinventing the wheel (like with the form styling) and making things prettier in general.
#### [implemented nicer flexible grid for cat images](https://github.com/chrisvfritz/look_at_cats/commit/a0283c37432217568b446b156db3e371280901f8)

I used a JS library called Freewall, which works a little funky, but allows us to show a much nicer grid of randomly sized images.
## Questions?

Please don't hesitate to let me know if you have any questions or comments regarding the changes I made and once again, fantastic job! This is definitely the best Rails app I've looked at so far.

**Comment by stuartpearman** [comment]
Hi Chris,

Thanks so much! The image columns really bothered me, so I'm especially
excited to see that fix. Slim is awesome and the bootstrap-sass gem sounds
like something I would benefit a lot from as well. I haven't had a chance
yet to see the changes in action, but I'm looking forward to it. I was
actually in the middle of emailing you earlier when you sent this. I wanted
to ask if you ever offer independent studies. There are a few things I
would really like to learn outside of the scope of this class/ the M&I
curriculum and I think you may have some helpful insight. Here are a few
things to get a better idea of what I'm talking about:

1) Making an ECommerce website
2) Accessing, working with, and visualizing big data
3) Application development in IOS and Android

These are just a few things I have been thinking about looking into, though
there are more. Let me know what you think!

Thanks again,

Stuart Pearman
pearmans@msu.edu

**Comment by chrisvfritz** [comment]
Glad you found the pull request helpful! I'm writing you a private email right now regarding the possibility of an independent study.
